apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: travism26/auth # Change this to your dockerhub username / image name
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: KAFKA_BROKER
              value: 'systems-kafka-cluster-kafka-bootstrap:9092' # Update with your broker address and port
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: KAFKA_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-kafka-user-secret # Updated to match your secret name
            #       key: username
            # - name: KAFKA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-kafka-user-secret # Updated to match your secret name
            #       key: password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
