apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: travism26/user # Change this to your dockerhub username / image name
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://user-mongo-srv:27017/user'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BROKER
              value: 'systems-kafka-cluster-kafka-bootstrap:9092' # Update with your broker address and port
            - name: REDIS_HOST
              value: 'user-redis-srv'
            # - name: KAFKA_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-kafka-user-secret # Updated to match your secret name
            #       key: username
            # - name: KAFKA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-kafka-user-secret # Updated to match your secret name
            #       key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
