apiVersion: v1
kind: Secret
metadata:
  name: my-kafka-user-secret
  namespace: default # Ensure the namespace is correct
type: Opaque
data:
  password: cmlja2ptcw== # Base64-encoded password
  username: c3VwZXJzZWN1cmU= # Base64-encoded username

# Obvously you should not store your secrets in plain text in your yaml files.
# but for the sake of testing, we will do so. :)
# echo -n "rickjms" | base64
# echo -n "supersecure" | base64
